### ISSUE TITLE
Incluir o recurso para coleta com filtro por categoria

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp2iahx-export#1]
Demanda derivado do ocomon 2797(http://suporte.bvs.br/ocomon/geral/mostra_consulta.php?numero=2797&id=1661511401992091283277175255), projeto  BVS Bioética e Diplomacia em Saúde para coletas dos conteúdos do Ciclo de Desbates do portal do Nethis (http://bioeticaediplomacia.org/pt/category/ciclo-de-debates/) no iahx da BVS Bioética e Diplomacia em Saúde (http://pesquisa.bvsalud.org/bioeticaediplomacia/)

**Comment by wilsonmoura** [comment]
Filtro por nome de categoria foi implementado de acordo com o commit 96f468db44682502cbf0c4437eea077467033e80
